version: '3'
services:
  bot:
    image: bot_image
    build: ./bot_image
    container_name: bot
    depends_on:
      - db
      - db_repl
    networks:
      - custom_network
    env_file:
      - .env
    volumes:
      - pg_logs:/var/log/

  db:
    image: db_image
    build: ./db_image
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - DB_DATABASE=${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - pg_logs:/var/log/
    networks:
      - custom_network

  db_repl:
    image: db_repl_image
    build: ./db_repl_image
    container_name: ${DB_REPL_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATABASE=${DB_DATABASE}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - custom_network
    volumes:
      - db_repl_data:/var/lib/postgresql/data

volumes:
  db_data:
    name: db_data
  db_repl_data:
    name: db_repl_data
  pg_logs:

networks:
  custom_network:
    driver: bridge
    name: custom_network
